Exception on /configuration [GET]
Traceback (most recent call last):
  File "C:\Users\david.verdejo.TOOLFACTORY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\david.verdejo.TOOLFACTORY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\david.verdejo.TOOLFACTORY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\david.verdejo.TOOLFACTORY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\david.verdejo.TOOLFACTORY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\david.verdejo.TOOLFACTORY\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\david.verdejo.TOOLFACTORY\Google Drive\Personal\scripts\python\traveltoolssl\web.py", line 92, in configuration
    return render_template('response.html',showlogs),200
TypeError: render_template() takes 1 positional argument but 2 were given
